### ISSUE TITLE
noise handling in CEM

### ISSUE THREAD

**Issue by usstdqq** [YuvalBahat/Explorable-Super-Resolution#12]
Hello again : )

when training and testing with CEM warped SR models, I found that if the input LR image has noise, then the CEM output is also noisy. An example of LR input and HR CEM output:
![0801](https://user-images.githubusercontent.com/6977304/108588046-0542d580-730c-11eb-9350-a28b6dede1ac.png)
![0801_0_0](https://user-images.githubusercontent.com/6977304/108588050-0a078980-730c-11eb-84cc-9e9f7a342186.png)

Such behavior is desirable to keep the fidelity. however, noise exists in many SR settings so it is not desirable to make HR output follow the noise. I am wondering is there something we can do in CEM to avoid the fidelity to noise?

**Comment by YuvalBahat** [comment]
Hi :)

That's a very good question. As you wrote, an undesired byproduct of the CEM is that it makes the SR output consistent with the noise in the LR input. This is because the current design of the CEM assumes no noise. This works for some images, but fails whenever there is strong noise, e.g. in images taken under low light conditions, or images suffering from compression artifacts.

To tackle this issue, one needs to redesign the CEM to handle noise, but this would require defining the notion of consistency for the presence of noise.

I hope this helps.

**Comment by usstdqq** [comment]
Thanks for your reply. It seems that noise handling in CEM and some relative soft fidelity constraint are out of the scope of this repo. so closing this issue.
