### ISSUE TITLE
Training error, ask for help!

### ISSUE THREAD

**Issue by Yu-Wang-0801** [YuvalBahat/Explorable-Super-Resolution#9]
![image](https://user-images.githubusercontent.com/49390007/104995211-e4633800-5a60-11eb-9eaa-70bb11f97fec.png)
When I retrained the model, I followed your steps to the last step, but the following error occurred, how to solve this? Look forward to your careful answer, thank you!

**Comment by YuvalBahat** [comment]
Thanks for letting me know about this problem. It seems to be due to an invalid "path" field in the datasets configuration. I changed the json file. Could you let me know if the problem is fixed?

**Comment by Yu-Wang-0801** [comment]
![image](https://user-images.githubusercontent.com/49390007/105045703-2a40f000-5aa3-11eb-84e3-9dc85192ec8b.png)
Thank you very much for your reply. I have solved the previous problem, but now I have a new problem. How to make the number of image blocks clipped by HR consistent with the number of LR? Is the cropping size and step size set by HR-LR 4 times the way to crop the image? Hope to get your reply, thank you!

**Comment by YuvalBahat** [comment]
It seems that you have a different number of images in the LR and HR image folders. I suspect this has to do with the way you prepare the data for the training, probably due to a problem in my explanation. I apologize for that, I would be grateful for your help in understanding the exact problem.
If I understand correctly, you create the image crops by running the extract_subimgs_single.py script. My questions is, how did you obtain the pairs of HR and LR images in the first place?

I hope with your help I'll be able to resolve this problem quickly.
Thanks :)

**Comment by Yu-Wang-0801** [comment]
Thank you very much for your reply again. My DIV2K training dataset is configured as follows: the HR data set has 800pieces of training sets, and the corresponding LR datasets are obtained by Bicubic operation. Then I use extract_subimgs_single.py to crop. The clipping parameter of HR is crop_sz = 480  step = 240, and the corresponding LR clipping parameter is crop_sz = 120  Step = 60. With regard to the other parameters, I did not change them, so at this point I have a situation where the number of HR and LR are not equal. So I would like to ask you, where is my problem? 
Look forward to your careful answer, thank you very much!

**Comment by YuvalBahat** [comment]
Thanks for your reply.

To fix this program, I changed the data preparation process as follows:
1.Use extract_subimgs_single.py on your HR dataset to create a folder of HR sub-images.
2.Use generate_mod_LR_bic.py on the newly created HR sub-images. This would create two new folders with (an equal number of) corresponding HR-LR pairs.
3.Use generate_lmdb.py to convert the sub-images into lmdb files for faster loading. This should be done twice, once with HR_images flag set to True and once with the HR_images flag set to False, to create lmdb files for both HR and LR sub-images, respectively.

I updated the three above mentioned scripts so that you only need to update the dataset_root_path field in each one of them, and you should be ready to go. Please check out the new versions.

I'd be grateful if you could try this and let me know everything worked for you.

Thanks,
Yuval

**Comment by Yu-Wang-0801** [comment]
![image](https://user-images.githubusercontent.com/49390007/105170264-a6950b00-5b57-11eb-925c-d46c1793f538.png)
Thank you very much for your reply! 
I reprocessed the data set and started training.  But I have a question, as shown in the figure, I have been waiting for about ten minutes at this time, but the training process did not continue to the next iteration, and I used 4 1080Ti GPU, is this process normal?  What was the GPU configuration during your training?  I didn't see your GPU usage in the paper. 
Looking forward to your reply, thank you.

**Comment by YuvalBahat** [comment]
Hi,
The log says it is taking approximately 4.65 seconds per optimization step, and it is printing every 100 steps, which means it should print every ~8 minutes. If it does not, you can check the GPU usage to try to understand why things are stuck.
In my training I used an NVIDIA GeForce 2080 GPU, though I'm not sure what was the duration of each step.

I hope this helps...

**Comment by Zuomy826** [comment]
> ![image](https://user-images.githubusercontent.com/49390007/105045703-2a40f000-5aa3-11eb-84e3-9dc85192ec8b.png) Thank you very much for your reply. I have solved the previous problem, but now I have a new problem. How to make the number of image blocks clipped by HR consistent with the number of LR? Is the cropping size and step size set by HR-LR 4 times the way to crop the image? Hope to get your reply, thank you!

您好 我想问一下第一个问题 您怎么解决的呀
